version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    command: ["npm", "start"]
    ports:
      - "8080:8080"
    networks:
      - shadownet

  frontend:
    build: ./frontend-ui
    container_name: frontend
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    networks:
      - shadownet

  ml:
    build: ./ML
    container_name: ml
    command: ["python", "app.py"]
    ports:
      - "5000:5000"
    networks:
      - shadownet

  osint:
    build: ./osintx
    container_name: osint
    command: ["python", "osint_service.py"]
    networks:
      - shadownet

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: shadow
      POSTGRES_PASSWORD: trace
      POSTGRES_DB: shadowtrace
    ports:
      - "5432:5432"
    networks:
      - shadownet

networks:
  shadownet:
    driver: bridge
